---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resourcequota-dev.yaml
  - limitrange-dev.yaml
  - resourcequota-staging.yaml
  - limitrange-staging.yaml
  - resourcequota-prod.yaml
  - limitrange-prod.yaml
