#!/usr/bin/env bash
#
# cluster-up.sh — create the local kind development cluster.
#
# Idempotent: if the cluster already exists it reports that and exits 0 rather
# than recreating it. Waits until the cluster is genuinely usable (all nodes Ready
# AND CoreDNS available), not merely until `kind create` returns.
#
# Usage:
#   ./cluster-up.sh [--recreate] [--yes] [--help]
#
# Environment:
#   CLUSTER_NAME      kind cluster name          (default: kubernetes-platform)
#   KIND_NODE_IMAGE   pin the Kubernetes version (default: kind's own default)
#                     e.g. kindest/node:v1.34.0@sha256:<digest>
#   WAIT_TIMEOUT      seconds to wait for readiness (default: 300)
set -Eeuo pipefail

# shellcheck source=scripts/lib/common.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
trap 'on_error $LINENO' ERR

readonly WAIT_TIMEOUT="${WAIT_TIMEOUT:-300}"
RECREATE=0
ASSUME_YES="${ASSUME_YES:-0}"

usage() {
  cat <<EOF
Usage: ${0##*/} [options]

Creates the local kind cluster defined by infra/kind/cluster.yaml.

Options:
  --recreate   Delete an existing cluster of the same name first (destructive)
  --yes, -y    Do not prompt for confirmation (for --recreate / automation)
  --help, -h   Show this help

Environment:
  CLUSTER_NAME=${CLUSTER_NAME}
  KIND_NODE_IMAGE=${KIND_NODE_IMAGE:-<kind default>}
  WAIT_TIMEOUT=${WAIT_TIMEOUT}
EOF
}

parse_args() {
  while (( $# > 0 )); do
    case "$1" in
      --recreate)  RECREATE=1 ;;
      --yes|-y)    ASSUME_YES=1 ;;
      --help|-h)   usage; exit 0 ;;
      *)           usage >&2; die "unknown argument: $1" ;;
    esac
    shift
  done
}

create_cluster() {
  local -a args=(
    create cluster
    --name "${CLUSTER_NAME}"
    --config "${KIND_CONFIG}"
    --wait "60s"
  )

  if [[ -n "${KIND_NODE_IMAGE}" ]]; then
    log "pinning node image: ${KIND_NODE_IMAGE}"
    args+=(--image "${KIND_NODE_IMAGE}")
  else
    log "using kind's default node image (pin with KIND_NODE_IMAGE — see infra/kind/README.md)"
  fi

  log "creating cluster '${CLUSTER_NAME}' — this takes 1–3 minutes on first run"
  kind "${args[@]}"
}

# `kind create --wait` only waits for the control plane. These are the conditions
# that actually mean "I can deploy something": every node Ready, and CoreDNS up —
# without DNS, everything scheduled afterwards fails in confusing ways.
wait_until_usable() {
  wait_for "${WAIT_TIMEOUT}" "all nodes Ready" \
    kubectl --context "${KUBE_CONTEXT}" wait --for=condition=Ready nodes --all --timeout=30s

  wait_for "${WAIT_TIMEOUT}" "CoreDNS available" \
    kubectl --context "${KUBE_CONTEXT}" -n kube-system wait \
      --for=condition=Available deployment/coredns --timeout=30s
}

# Record what actually came up. Without this, an unpinned cluster's Kubernetes
# version is invisible after the fact — which makes "worked yesterday" hard to debug.
record_cluster_info() {
  mkdir -p "${LOCAL_STATE_DIR}"
  local info="${LOCAL_STATE_DIR}/cluster-info.txt"
  {
    echo "# Generated by scripts/cluster-up.sh — not committed (.gitignore)"
    echo "created:        $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "cluster:        ${CLUSTER_NAME}"
    echo "context:        ${KUBE_CONTEXT}"
    echo "node_image:     ${KIND_NODE_IMAGE:-<kind default>}"
    echo "kind_version:   $(kind version 2>/dev/null | awk '{print $2}')"
    echo "k8s_version:    $(kubectl --context "${KUBE_CONTEXT}" get nodes \
                              -o jsonpath='{.items[0].status.nodeInfo.kubeletVersion}' 2>/dev/null)"
    echo "nodes:          $(kubectl --context "${KUBE_CONTEXT}" get nodes --no-headers 2>/dev/null | wc -l | tr -d ' ')"
  } > "${info}"
  success "recorded cluster info → ${info#"${REPO_ROOT}/"}"
}

next_steps() {
  heading "Cluster ready"
  kubectl --context "${KUBE_CONTEXT}" get nodes -o wide

  cat <<EOF

  Context:  ${KUBE_CONTEXT}  (already set as current)

  Next:
    make status                 show nodes, system pods, context
    kubectl get pods -A         everything running in the cluster
    make down                   tear it down

  Phase 2 will add ingress-nginx, metrics-server, namespaces, RBAC, and quotas.
  See ROADMAP.md.
EOF
}

main() {
  parse_args "$@"

  "${REPO_ROOT}/scripts/preflight.sh"

  if cluster_exists; then
    if (( RECREATE )); then
      warn "cluster '${CLUSTER_NAME}' exists and --recreate was given"
      confirm "Delete and recreate cluster '${CLUSTER_NAME}'? All cluster state will be lost." \
        || die "aborted"
      log "deleting existing cluster '${CLUSTER_NAME}'"
      kind delete cluster --name "${CLUSTER_NAME}"
    # A failed `kind create` leaves its containers behind, so the cluster still
    # shows up in `kind get clusters`. Reporting "already exists, nothing to do"
    # for a half-built cluster would hand the user a broken environment and call
    # it success — so existence is not enough, it has to actually respond.
    elif ! kubectl --context "${KUBE_CONTEXT}" get nodes >/dev/null 2>&1; then
      err "cluster '${CLUSTER_NAME}' exists but its API server is not responding"
      err "this usually means a previous 'make up' failed partway through"
      log "rebuild it with:  make recreate"
      exit 1
    else
      success "cluster '${CLUSTER_NAME}' already exists — nothing to do"
      log "use --recreate to rebuild it, or 'make down' to remove it"
      kubectl config use-context "${KUBE_CONTEXT}" >/dev/null 2>&1 || true
      exit 0
    fi
  fi

  create_cluster
  kubectl config use-context "${KUBE_CONTEXT}" >/dev/null
  wait_until_usable
  record_cluster_info
  next_steps
}

main "$@"
